version: '3.3'
name: cicd
services:
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    restart: on-failure
    ports:
      - 5000:5000
    volumes:
      - jenkins_home:/var/jenkins_home
  proxy:
    build: ./proxy
    restart: always
    env_file: .env
    depends_on:
      - jenkins
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./proxy/first_ssl.conf:/first_ssl.conf
      - ./proxy/prod.conf:/prod.conf.template
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    command: sh -c "cp /first_ssl.conf /etc/nginx/conf.d/default.conf &&
                    nginx -g 'daemon on;' &&
                    /certbot_first_ssl.sh &&
                    nginx -s stop &&
                    envsubst < /prod.conf.template > /etc/nginx/conf.d/default.conf &&
                    crond -b -l 8 -L /var/log/cron.log &&
                    nginx -g 'daemon off;'"
volumes:
  jenkins_home:
  certbot-etc:
  certbot-var:
